#ifndef KEY_HPP
#define KEY_HPP

enum class MouseCode : int {
    Button1         = GLFW_MOUSE_BUTTON_1,
    Button2         = GLFW_MOUSE_BUTTON_2,
    Button3         = GLFW_MOUSE_BUTTON_3,
    Button4         = GLFW_MOUSE_BUTTON_4,
    Button5         = GLFW_MOUSE_BUTTON_5,
    Button6         = GLFW_MOUSE_BUTTON_6,
    Button7         = GLFW_MOUSE_BUTTON_7,
    Button8         = GLFW_MOUSE_BUTTON_8,
    Left            = GLFW_MOUSE_BUTTON_LEFT,
    Right           = GLFW_MOUSE_BUTTON_RIGHT,
    Middle          = GLFW_MOUSE_BUTTON_MIDDLE
};

enum class Key {
    Unknown      = -1,
    Space        = 32,
    Apostrophe   = 39,
    Comma        = 44,
    Minus        = 45,
    Period       = 46,
    Slash        = 47,
    Num0         = 48,
    Num1         = 49,
    Num2         = 50,
    Num3         = 51,
    Num4         = 52,
    Num5         = 53,
    Num6         = 54,
    Num7         = 55,
    Num8         = 56,
    Num9         = 57,
    A            = 65,
    B            = 66,
    C            = 67,
    D            = 68,
    E            = 69,
    F            = 70,
    G            = 71,
    H            = 72,
    I            = 73,
    J            = 74,
    K            = 75,
    L            = 76,
    M            = 77,
    N            = 78,
    O            = 79,
    P            = 80,
    Q            = 81,
    R            = 82,
    S            = 83,
    T            = 84,
    U            = 85,
    V            = 86,
    W            = 87,
    X            = 88,
    Y            = 89,
    Z            = 90,
    Escape       = 256,
    Enter        = 257,
    Tab          = 258,
    Backspace    = 259,
    Insert       = 260,
    Delete       = 261,
    Right        = 262,
    Left         = 263,
    Down         = 264,
    Up           = 265,
};

#endif
